### ISSUE TITLE
Práctica de visualización de datos - Edwin Ortiz Cruz 

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicosavanzados-ide#1]
[Practica de consulta de datos en Visual_4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicosavanzados-ide/files/8721743/Practica.de.consulta.de.datos.en.Visual_4US.pdf)

**Comment by JoseABCruz** [comment]
Portada: 25%
Procedimiento: 25%
Lista de Figuras: 25%
Conlusiones: 25%

Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
