### ISSUE TITLE
Práctica2-MySqlC#-consulta

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicosavanzados-ide#2]
[ConsultaBaseDeDatos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicosavanzados-ide/files/8919197/ConsultaBaseDeDatos.pdf)

**Comment by JoseABCruz** [comment]
Portada: 25%
Procedimiento: 25%
Lista de Figuras: 25%
Conlusiones: 25%

Calificación: 20%

**Comment by josealfredo79** [comment]
No esta subida la practica...favor de subir nuevamente,...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
