### ISSUE TITLE
Practica-ConsultaDeDatos

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicosavanzados-ide#3]
[Practica-ConsultaDeDatos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-topicosavanzados-ide/files/8723955/Practica-ConsultaDeDatos.pdf)

**Comment by JoseABCruz** [comment]
Portada: 25%
Procedimiento: 25%
Lista de Figuras: 25%
Conlusiones: 25%

Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
